const CREATE_USER = "CREATE_USER";
const READ_USER = "READ_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";

const CREATE_UBICATION = "CREATE_UBICATION";
const READ_UBICATION = "READ_UBICATION";
const UPDATE_UBICATION = "UPDATE_UBICATION";
const DELETE_UBICATION = "DELETE_UBICATION";

const HOST = 'http://localhost:3000/api';

export default {
  CREATE_USER,
  READ_USER,
  UPDATE_USER,
  DELETE_USER,
  CREATE_UBICATION,
  READ_UBICATION,
  UPDATE_UBICATION,
  DELETE_UBICATION,
  HOST
};
